--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: eureka-service-registry
    version: v1
  name: eureka-service-registry
spec: 
  strategy: # Default, so usually not specified
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # specifies the maximum number of Pods that can be created over the desired number of Pods
      maxUnavailable: 25% #specifies the maximum number of Pods that can be unavailable during the update process
  replicas: 1
  selector: 
    matchLabels: 
      app: eureka-service-registry
      version: v1
  template: 
    metadata: 
      labels: 
        app: eureka-service-registry
        version: v1

    spec: 

      containers: 
        - 
          image: "ragabms/eureka-service-registry:1"
          imagePullPolicy: Always
          name: eureka-service-registry
          ports: 
#          - containerPort: 8010   
          - name: httpport
            containerPort: 8761
            hostPort: 8761 
            
---
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: eureka-service-registry
    version: v1
  name: eureka-service-registry
spec: 
  ports: 
    - 
      name: http
      port: 8761
      targetPort: 8761
  selector: 
    app: eureka-service-registry
    version: v1
  type: NodePort
     
